@extends('layouts.public')
@section('title', 'Purchase '.$offer->name)
@section('content')
@php($money = app(\App\Domain\Money\MoneyService::class))
<div class="card"><h1>{{ $offer->name }}</h1><p>{{ $offer->description }}</p><p><strong>@if($offer->discount_type->value === 'fixed'){{ $money->format($offer->amount_minor, $organization->currency) }} value @else{{ rtrim(rtrim(number_format($offer->percentage_bps / 100, 2), '0'), '.') }}% off @endif</strong> · costs {{ $money->format($offer->purchase_price_minor, $organization->currency) }}</p><p>{{ $offer->applies_to_all ? 'Valid for all available appointments.' : 'Valid for: '.$offer->appointmentTypes->pluck('name')->join(', ') }} · {{ $offer->expires_on ? 'Expires '.$offer->expires_on->format('F j, Y') : 'No expiration date' }}</p></div>
<form method="post" action="{{ route('public.coupons.purchase', [$organization->slug, $offer]) }}" class="form-stack mt-4">@csrf
<div class="section-card"><h2>Purchaser</h2><div class="row"><div class="field"><label for="purchaser_name">Name</label><input id="purchaser_name" name="purchaser_name" value="{{ old('purchaser_name') }}" required maxlength="240"></div><div class="field"><label for="purchaser_email">Email</label><input id="purchaser_email" type="email" name="purchaser_email" value="{{ old('purchaser_email') }}" required maxlength="254"></div></div></div>
<div class="section-card"><h2>Recipient &amp; delivery</h2><div class="row"><div class="field"><label for="recipient_name">Recipient name</label><input id="recipient_name" name="recipient_name" value="{{ old('recipient_name') }}" maxlength="240"></div><div class="field"><label for="recipient_email">Recipient email</label><input id="recipient_email" type="email" name="recipient_email" value="{{ old('recipient_email') }}" maxlength="254"></div></div><div class="field"><label for="message">Message</label><textarea id="message" name="message" rows="3" maxlength="5000">{{ old('message') }}</textarea></div><div class="field"><label for="delivery_method">Delivery</label><select id="delivery_method" name="delivery_method">@foreach($deliveryMethods as $method)<option value="{{ $method->value }}" @selected(old('delivery_method') === $method->value)>{{ $method->label() }}</option>@endforeach</select></div></div>
<div class="section-card"><h2>Protected page</h2><p class="muted">Set the password needed to view the coupon. It is never included in the delivery email; share it separately.</p><div class="row"><div class="field"><label for="password">Password</label><input id="password" type="password" name="password" required minlength="8" maxlength="200"></div><div class="field"><label for="password_confirmation">Confirm password</label><input id="password_confirmation" type="password" name="password_confirmation" required></div></div></div>
<div class="section-card"><h2>Payment</h2>@forelse($providers as $provider)<label class="inline-check"><input type="radio" name="provider" value="{{ $provider->value }}" @checked($loop->first) required> {{ $provider->label() }}</label>@empty<p>No online payment provider is currently available. Contact {{ $organization->name }}.</p>@endforelse<p class="small muted">By purchasing, you acknowledge that gift cards/coupons cannot be cancelled or refunded at buyer request. An unused code may only be destroyed and refunded by {{ $organization->name }} through its administrative console.</p></div>
@if($providers !== [])<button class="btn btn-primary" type="submit">Pay {{ $money->format($offer->purchase_price_minor, $organization->currency) }}</button>@endif <a class="btn" href="{{ route('public.coupons.index', $organization->slug) }}">Back</a>
</form>
@endsection
