@extends('layouts.app')
@section('title', 'Gift cards & coupons')
@section('content')
@php($money = app(\App\Domain\Money\MoneyService::class))
<div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h2 mb-1">Gift cards & coupons</h1><p class="text-body-secondary mb-0">Sell public offers, issue codes manually, and destroy unused codes with an auditable refund.</p></div><a class="btn btn-outline-secondary" href="{{ route('public.coupons.index', $organization->slug) }}" target="_blank">Public page</a></div>

<div class="row g-4">
<div class="col-xl-6"><div class="card shadow-sm"><div class="card-body"><h2 class="h4">Add a purchasable offer</h2>
<form method="post" action="{{ route('coupons.offers.store') }}" class="vstack gap-3">@csrf
<div><label class="form-label">Name</label><input class="form-control" name="name" value="{{ old('name') }}" required maxlength="160"></div>
<div><label class="form-label">Description</label><textarea class="form-control" name="description" rows="2">{{ old('description') }}</textarea></div>
<div class="row g-3"><div class="col-md-4"><label class="form-label">Benefit</label><select class="form-select coupon-kind" name="discount_type"><option value="fixed">Fixed amount</option><option value="percentage">Percentage</option></select></div><div class="col-md-4"><label class="form-label">Fixed value ({{ $organization->currency }})</label><input class="form-control coupon-fixed" name="amount" inputmode="decimal"></div><div class="col-md-4"><label class="form-label">Percentage</label><input class="form-control coupon-percent" name="percentage" inputmode="decimal" placeholder="10"></div></div>
<div><label class="form-label">Purchase price ({{ $organization->currency }})</label><input class="form-control" name="purchase_price" inputmode="decimal" required></div>
@include('coupons.partials.applicability', ['prefix' => 'offer'])
<div><label class="form-label">Expiration date <span class="text-body-secondary">optional</span></label><input class="form-control" type="date" name="expires_on"></div>
<div class="form-check"><input class="form-check-input" type="checkbox" name="is_public" value="1" id="offer_public" checked><label class="form-check-label" for="offer_public">Show this offer on the public purchase page</label></div>
<button class="btn btn-primary" type="submit">Add offer</button></form></div></div></div>

<div class="col-xl-6"><div class="card shadow-sm"><div class="card-body"><h2 class="h4">Create manually</h2>
<form method="post" action="{{ route('coupons.manual.store') }}" class="vstack gap-3">@csrf
<div class="row g-3"><div class="col-md-4"><label class="form-label">Benefit</label><select class="form-select coupon-kind" name="discount_type"><option value="fixed">Fixed amount</option><option value="percentage">Percentage</option></select></div><div class="col-md-4"><label class="form-label">Fixed value ({{ $organization->currency }})</label><input class="form-control coupon-fixed" name="amount" inputmode="decimal"></div><div class="col-md-4"><label class="form-label">Percentage</label><input class="form-control coupon-percent" name="percentage" inputmode="decimal" placeholder="10"></div></div>
@include('coupons.partials.applicability', ['prefix' => 'manual'])
<div><label class="form-label">Expiration date <span class="text-body-secondary">optional</span></label><input class="form-control" type="date" name="expires_on"></div>
<div class="row g-3"><div class="col-md-6"><label class="form-label">Recipient name</label><input class="form-control" name="recipient_name"></div><div class="col-md-6"><label class="form-label">Recipient email</label><input class="form-control" type="email" name="recipient_email"></div></div>
<div><label class="form-label">Message</label><textarea class="form-control" name="message" rows="2"></textarea></div>
<div><label class="form-label">Delivery</label><select class="form-select" name="delivery_method">@foreach($deliveryMethods as $method)<option value="{{ $method->value }}">{{ $method->label() }}</option>@endforeach</select></div>
<div class="row g-3"><div class="col-md-6"><label class="form-label">Protected-page password</label><input class="form-control" type="password" name="password" required minlength="8"></div><div class="col-md-6"><label class="form-label">Confirm password</label><input class="form-control" type="password" name="password_confirmation" required></div></div>
<p class="small text-body-secondary mb-0">Passwords are never emailed. Share it separately with the recipient.</p><button class="btn btn-primary" type="submit">Create coupon</button></form></div></div></div>
</div>

<div class="card shadow-sm mt-4"><div class="card-body"><h2 class="h4">Public offers</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Name</th><th>Benefit</th><th>Price</th><th>Scope</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($offers as $offer)<tr><td>{{ $offer->name }}</td><td>{{ $offer->discount_type->value === 'fixed' ? $money->format($offer->amount_minor, $organization->currency) : rtrim(rtrim(number_format($offer->percentage_bps / 100, 2), '0'), '.').'%' }}</td><td>{{ $money->format($offer->purchase_price_minor, $organization->currency) }}</td><td>{{ $offer->applies_to_all ? 'All appointments' : $offer->appointmentTypes->pluck('name')->join(', ') }}</td><td>{{ $offer->is_active ? 'Active' : 'Disabled' }}{{ $offer->is_public ? ' · public' : ' · hidden' }}</td><td><div class="d-flex gap-1"><form method="post" action="{{ route('coupons.offers.toggle', $offer) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">{{ $offer->is_active ? 'Disable' : 'Enable' }}</button></form><form method="post" action="{{ route('coupons.offers.toggle', $offer) }}">@csrf @method('PATCH')<input type="hidden" name="field" value="visibility"><button class="btn btn-sm btn-outline-secondary">{{ $offer->is_public ? 'Hide' : 'Publish' }}</button></form></div></td></tr>@empty<tr><td colspan="6" class="text-body-secondary">No offers yet.</td></tr>@endforelse
</tbody></table></div></div></div>

<div class="card shadow-sm mt-4"><div class="card-body"><h2 class="h4">Issued codes</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Code</th><th>Recipient</th><th>Value / balance</th><th>Status</th><th>Source</th><th>Actions</th></tr></thead><tbody>
@forelse($coupons as $coupon)<tr><td><code>{{ $coupon->code }}</code></td><td>{{ $coupon->recipient_name ?: '—' }}<br><span class="small text-body-secondary">{{ $coupon->recipient_email }}</span></td><td>@if($coupon->discount_type->value === 'fixed'){{ $money->format($coupon->amount_minor, $organization->currency) }} / {{ $money->format($coupon->remaining_amount_minor, $organization->currency) }}@else{{ rtrim(rtrim(number_format($coupon->percentage_bps / 100, 2), '0'), '.' ) }}%@endif</td><td>{{ $coupon->status->label() }}@if($coupon->expires_on)<br><span class="small">expires {{ $coupon->expires_on->format('Y-m-d') }}</span>@endif</td><td>{{ ucfirst($coupon->source->value) }}</td><td><div class="d-flex flex-wrap gap-2"><a class="btn btn-sm btn-outline-secondary" href="{{ route('coupons.show', $coupon) }}">Print</a>@if($coupon->redemptions->isEmpty() && !in_array($coupon->status->value, ['used','destroyed']))<form method="post" action="{{ route('coupons.destroy', $coupon) }}" class="d-flex gap-1" onsubmit="return confirm('Destroy this unused coupon? A completed purchase will be refunded.')">@csrf @method('DELETE')<input class="form-control form-control-sm" name="reason" required placeholder="Reason"><button class="btn btn-sm btn-danger">Destroy</button></form>@endif @foreach($coupon->refunds->whereIn('status', [\App\Enums\PaymentRefundStatus::Pending, \App\Enums\PaymentRefundStatus::Failed]) as $refund)<form method="post" action="{{ route('coupons.refunds.retry', [$coupon, $refund]) }}">@csrf<button class="btn btn-sm btn-warning">Retry refund</button></form>@endforeach</div></td></tr>@empty<tr><td colspan="6" class="text-body-secondary">No codes issued yet.</td></tr>@endforelse
</tbody></table></div></div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('.coupon-kind').forEach(select=>{const sync=()=>{const form=select.closest('form');form.querySelector('.coupon-fixed').disabled=select.value!=='fixed';form.querySelector('.coupon-percent').disabled=select.value!=='percentage';};select.addEventListener('change',sync);sync();});document.querySelectorAll('.coupon-applies-all').forEach(box=>{const sync=()=>{box.closest('.coupon-applicability').querySelector('.coupon-selected-types').hidden=box.checked;};box.addEventListener('change',sync);sync();});</script>@endpush
